[tool.poetry]
name = "glyphworks"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "n"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.5"
django-extensions = "^3.1.5"
django-webpack-loader = "^1.5.0"
daphne = "^3.0.2"
gunicorn = "^20.1.0"
flake8 = "^4.0.1"
psycopg2 = "^2.9.3"
factory-boy = "^3.2.1"
ipython = "^8.4.0"
graphene-django = "^2.15.0"

[tool.poetry.dev-dependencies]
pip-audit = "^2.3.3"
watchfiles = "^0.16.1"
django-watchfiles = "^0.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
