[tool.poetry]
name = "glyphworks"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "n"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.5"
django-extensions = "^3.1.5"
django-webpack-loader = "^1.5.0"
daphne = "^3.0.2"
gunicorn = "^20.1.0"
flake8 = "^4.0.1"
psycopg2 = "^2.9.3"
factory-boy = "^3.2.1"
ipython = "^8.4.0"

[tool.poetry.dev-dependencies]
pywatchman = "^1.4.1"
pip-audit = "^2.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
