version: "3.8"

services:

  python:
    image: &image kwiliarty/glyphworks:main-dev
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings.ci
    ports:
      - "${GW_PYTHON_PORT}:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      &volumes
      - node_modules:/node_modules
      - yarn_cache:/yarn_cache
      - type: bind
        source: ./../
        target: /usr/src/app

volumes:
  node_modules:
  yarn_cache:
