version: "3.8"

services:

  python:
    &python
    image: kwiliarty/glyphworks:main
    restart: always
    environment:
      - TZ=America/New_York
      - GW_ENV
      - GW_INSTANCE
      - SECRET_KEY
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - django
    depends_on:
      - db

  db:
    image: postgres:13.5-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - django
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  django:

volumes:
  postgres_data:
