version: "3.8"

services:

  python:
    &python
    image: kwiliarty/glyphworks:main
    restart: always
    environment:
      - TZ=America/New_York
      - GW_ENV
      - GW_INSTANCE
      - SECRET_KEY
    networks:
      - django
    volumes:
      - node_modules:/node_modules
      - yarn_cache:/yarn_cache
    depends_on:
      - db

  db:
    image: postgres:13.5-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - django
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  django:

volumes:
  postgres_data:
  node_modules:
  yarn_cache:
