version: "3.8"

services:

  python:
    image: &image kwiliarty/glyphworks:main-dev
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings.dev
      - VIRTUAL_HOST=glyphworks.dev.test
      - VIRTUAL_PORT=8000
    ports:
      - "${GW_PYTHON_PORT}:8000"
    expose:
      - 8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      &volumes
      - node_modules:/node_modules
      - yarn_cache:/yarn_cache
      - poetry_cache:/poetry_cache
      - jedi_cache:/xdg_cache/jedi
      - type: bind
        source: ./../
        target: /usr/src/app
      - type: bind
        source: ./../cypress/support/node_modules/axe-core
        target: /node_modules/axe-core
      - type: bind
        source: ./../cypress/support/node_modules/cypress-axe
        target: /node_modules/cypress-axe
    networks:
      - django
      - nginx

  python-test:
    image: *image
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ=America/New_York
      - GW_ENV=ci
      - GW_INSTANCE
      - DJANGO_SETTINGS_MODULE=main.settings.ci
      - CYPRESS_SERVER=True
      - SECRET_KEY
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '0:8000'
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - django
    volumes:
      *volumes
    depends_on:
      - db-test

  webpack:
    image: *image
    restart: always
    command: ['/node_modules/webpack/bin/webpack.js', '--config', 'webpack.config.js', '--watch', '--mode', 'development']
    networks:
      - django
    volumes:
      *volumes

  styleguidist:
    image: *image
    restart: always
    command: ['yarn', 'styleguidist', 'server']
    environment:
      - VIRTUAL_HOST=styleguidist.dev.test
      - VIRTUAL_PORT=443
    expose:
      - 6060
      - 443
    ports:
      - '6060:6060'
    networks:
      - django
      - nginx
    volumes:
      *volumes

  db-test:
    image: postgres:13.5-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - django
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  node_modules:
  yarn_cache:
  poetry_cache:
  jedi_cache:
  postgres_test_data:

networks:
  nginx:
    external:
      name: nginx-proxy
