# Generated by Django 4.0.4 on 2022-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glyphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='id',
        ),
        migrations.AddField(
            model_name='glyph',
            name='combining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glyph',
            name='group',
            field=models.CharField(choices=[('PC', 'pulmonic consonant'), ('NPC', 'non-pulmonic consonant'), ('OS', 'other symbol'), ('V', 'vowel'), ('D', 'diacritic'), ('SS', 'suprasegmental'), ('T', 'tone or word accent'), ('NOC', 'not on chart')], default='PC', max_length=100),
        ),
        migrations.AddField(
            model_name='glyph',
            name='hex_code',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='glyph',
            name='ipa_definition',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glyph',
            name='ipa_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glyph',
            name='ipa_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='glyph',
            name='slug',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='glyph',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
