# Generated by Django 4.1.6 on 2023-02-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glyphs', '0004_map_alter_glyph_ipa_definition_alter_glyph_ipa_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Mapping',
        ),
    ]
