# Generated by Django 4.1.7 on 2023-03-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glyphs', '0006_alter_glyph_ipa_definition_replacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSystem',
            fields=[
                ('proxy_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                     related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('parent', main.models.NamedForeignKey(blank=True, db_column='parent_uuid', null=True,
                     on_delete=django.db.models.deletion.CASCADE, related_name='children',
                     to='glyphs.writingsystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                     related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category', main.models.NamedForeignKey(blank=True, db_column='category_slug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='glyphs.phonecategory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                     related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('letter_type', models.CharField(choices=[('normal', 'Normal'), ('modifier', 'Modifier'), ('chao', 'Chao letter')], default='normal', max_length=100)),
                ('alphabet', main.models.NamedForeignKey(db_column='alphabet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='glyphs.writingsystem')),
                ('glyph', main.models.NamedForeignKey(db_column='glyph', null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='letters', to='glyphs.glyph')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                     related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('phone', main.models.NamedForeignKey(db_column='phone', null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='letters', to='glyphs.phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='glyphs',
        ),
        migrations.AlterModelOptions(
            name='glyph',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='replacement',
            name='unique_text_glyph_mapping',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='glyph',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='combining',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='group',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='ipa_definition',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='ipa_name',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='ipa_number',
        ),
        migrations.RemoveField(
            model_name='glyph',
            name='slug',
        ),
        migrations.AddField(
            model_name='glyph',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='glyph',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glyph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='glyph',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Alphabet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('glyphs.writingsystem',),
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('glyphs.writingsystem',),
        ),
        migrations.DeleteModel(
            name='Replacement',
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20, null=True)),
                ('mapping', main.models.NamedForeignKey(db_column='mapping', null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='replacements', to='glyphs.writingsystem')),
                ('letter', main.models.NamedForeignKey(db_column='letter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='glyphs.letter')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                     related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
