name: GlyphWorks CI
on: [push]
jobs:
  build-dev:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: build-dev
        run: |
          shopt -s expand_aliases
          mv docker/ci.env docker/override.env
          source ./glyphworks.sh
          gw-build-dev
  test:
    needs: [build-dev]
    runs-on: self-hosted
    steps:
      - name: launch
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-up
      - name: eslint
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-eslint
      - name: flake8
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-flake8
  build-prod:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: [build-dev, test]
    steps:
      - name: Build production image
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-build-prod
  shutdown:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [build-dev, test, build-prod]
    steps:
      - name: down
        run: |
          source ./glyphworks.sh
          docker-compose down
