name: GlyphWorks CI
on: [push]
concurrency:
  group: 'glyphworks'
  cancel-in-progress: false
jobs:
  build-dev:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build-dev
        run: |
          shopt -s expand_aliases
          cp docker/ci.env docker/override.env
          source ./glyphworks.sh
          gw-build-dev
  test:
    needs: [build-dev]
    runs-on: self-hosted
    steps:
      - name: launch
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-up
          sleep 3
          gw /node_modules/.bin/webpack --config webpack.config.js --mode development
          # gw chmod -R a+rwx main/assets/bundles/
      - name: eslint
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-eslint
      - name: flake8
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-flake8
      - name: yarn_audit
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-yarn-audit
      - name: pip-audit
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-pip-audit
      - name: jest
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-jest
      - name: unit-test
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-unit-test
      - name: cypress
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-cypress-run
  build-prod:
    runs-on: self-hosted
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    needs: [build-dev, test]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build production image
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-build-prod
          gw-push-prod
  shutdown:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [build-dev, test, build-prod]
    steps:
      - name: down
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw rm -r main/assets/bundles/
          docker-compose down --remove-orphans
