name: GlyphWorks CI
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: build-dev
        run: |
          shopt -s expand_aliases
          mv docker/ci.env docker/override.env
          source ./glyphworks.sh
          gw-build-dev
      - name: launch
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-up
      - name: eslint
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-eslint
      - name: flake8
        run: |
          shopt -s expand_aliases
          source ./glyphworks.sh
          gw-flake8
  shutdown:
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [test]
    steps:
      - name: down
        run: |
          source ./glyphworks.sh
          docker-compose down
